[2025-10-04T16:56:57.757+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-04T16:56:57.770+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: retail_mlops_data_pipeline.download_raw_data_kaggle manual__2025-10-04T16:56:50.000373+00:00 [queued]>
[2025-10-04T16:56:57.776+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: retail_mlops_data_pipeline.download_raw_data_kaggle manual__2025-10-04T16:56:50.000373+00:00 [queued]>
[2025-10-04T16:56:57.776+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-10-04T16:56:57.792+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): download_raw_data_kaggle> on 2025-10-04 16:56:50.000373+00:00
[2025-10-04T16:56:57.799+0000] {standard_task_runner.py:63} INFO - Started process 11629 to run task
[2025-10-04T16:56:57.801+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'retail_mlops_data_pipeline', 'download_raw_data_kaggle', 'manual__2025-10-04T16:56:50.000373+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/retail_mlops_data_pipeline.py', '--cfg-path', '/tmp/tmpg4ssgbme']
[2025-10-04T16:56:57.803+0000] {standard_task_runner.py:91} INFO - Job 26: Subtask download_raw_data_kaggle
[2025-10-04T16:56:57.840+0000] {task_command.py:426} INFO - Running <TaskInstance: retail_mlops_data_pipeline.download_raw_data_kaggle manual__2025-10-04T16:56:50.000373+00:00 [running]> on host ip-172-31-17-35.ec2.internal
[2025-10-04T16:56:57.901+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='retail_mlops_data_pipeline' AIRFLOW_CTX_TASK_ID='download_raw_data_kaggle' AIRFLOW_CTX_EXECUTION_DATE='2025-10-04T16:56:50.000373+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-04T16:56:50.000373+00:00'
[2025-10-04T16:56:57.901+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-04T16:56:57.912+0000] {logging_mixin.py:188} INFO - Starting download of mehmettahiraslan/customer-shopping-dataset...
[2025-10-04T16:56:57.912+0000] {logging_mixin.py:188} INFO - ERROR: Kaggle credentials (KAGGLE_USERNAME/KEY) are not set in the environment.
[2025-10-04T16:56:57.913+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-04T16:56:57.913+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow/dags/retail_mlops_data_pipeline.py", line 42, in download_data
    raise EnvironmentError("Kaggle credentials missing.")
OSError: Kaggle credentials missing.
[2025-10-04T16:56:57.917+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=retail_mlops_data_pipeline, task_id=download_raw_data_kaggle, execution_date=20251004T165650, start_date=20251004T165657, end_date=20251004T165657
[2025-10-04T16:56:57.931+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 26 for task download_raw_data_kaggle (Kaggle credentials missing.; 11629)
[2025-10-04T16:56:57.974+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-04T16:56:57.991+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-04T16:56:57.991+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
